### ISSUE TITLE
Web portal doesn't show any messages contained within a ticket (neither does source).

### ISSUE THREAD

**Issue by RhysB** [eartharoid/DiscordTickets-Portal#1]
**Describe the bug**
Web portal doesn't show any messages contained within a ticket (neither does source).

**To Reproduce**
Setup the DiscordTicket-Portal with DiscordTickets using the newest versions.

**Expected behavior**
Messages from a ticket to be displayed in the log.

**Screenshots**
https://imgur.com/a/EEXEiSw

**Comment by camdan-me** [comment]
I'm having the same issue. According to the logs, everything is fine, but when I actually check it it doesn't show any messages, just the channel name and topic. Using an unmodified version of the code.

**Comment by eartharoid** [comment]
This has been fixed with an update to the bot.
