### ISSUE TITLE
Wont show messages

### ISSUE THREAD

**Issue by GamenHaaDee** [eartharoid/DiscordTickets-Portal#7]
When closing a ticket i get the link to the web page and then there is nothing 

http://ticket.gelderlandrp.nl:8080/327492308377403393/807981295225405500

Not even the welcoming message

**Comment by eartharoid** [comment]
This should have been fixed in the newer versions of the bot.

**Comment by GamenHaaDee** [comment]
it isnt this is the newest version

**Comment by eartharoid** [comment]
@Quinten-Gelderland have you figured this out?

This was a known issue, but it was fixed with an update to the bot on the 13th Nov 2020 ([v2.1.2](https://github.com/eartharoid/DiscordTickets/releases/tag/v2.1.2)). If you downloaded the bot before then, you need to update it.

**Comment by GamenHaaDee** [comment]
Thnx imma try it out
